//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTSControl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
