//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTSControl.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPKanbanEntities : DbContext
    {
        public SPKanbanEntities()
            : base("name=SPKanbanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Departments> Departments { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TaskComments> TaskComments { get; set; }
        public DbSet<TaskPriorities> TaskPriorities { get; set; }
        public DbSet<Tasks> Tasks { get; set; }
        public DbSet<TaskStatuses> TaskStatuses { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserStatuses> UserStatuses { get; set; }
    }
}
