//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTSControl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatuses
    {
        public TaskStatuses()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
