//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTSControl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.TaskComments = new HashSet<TaskComments>();
        }
    
        public int TaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<int> AssignedToUserID { get; set; }
        public int CurrentStatusID { get; set; }
        public int PriorityID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ICollection<TaskComments> TaskComments { get; set; }
        public virtual TaskPriorities TaskPriorities { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
    }
}
