//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTSControl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.TaskComments = new HashSet<TaskComments>();
            this.Tasks = new HashSet<Tasks>();
            this.Tasks1 = new HashSet<Tasks>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> MistakeCount { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<TaskComments> TaskComments { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
        public virtual ICollection<Tasks> Tasks1 { get; set; }
        public virtual UserStatuses UserStatuses { get; set; }
    }
}
